def unnamed():
  step_count_79a61de7_355a_455c_8b99_5185226d8bae = 0
  thread Step_Counter_Thread_5dad381d_487e_4399_b174_b88593222771():
    while (True):
      step_count_79a61de7_355a_455c_8b99_5185226d8bae = step_count_79a61de7_355a_455c_8b99_5185226d8bae + 1
      sync()
    end
  end
  run Step_Counter_Thread_5dad381d_487e_4399_b174_b88593222771()
  set_tool_voltage(0)
  set_gravity([0.0, 0.0, 9.82])
  set_safety_mode_transition_hardness(1)
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(2.5,[0.0,0.0,0.14])
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 1)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  while (True):
    $ 1 "Robot Program"
    $ 2 "Script: coffee.script"
    port = 30000
    ip = "192.168.0.80"
    socket_name = "coffee"
    
    socket = socket_open(ip, port, socket_name)
  end
end
